apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sim-control-httproute
  namespace: smart-router
spec:
  parentRefs:
    - name: sr-gateway
      namespace: smart-router
  hostnames:
    - "__CONTROL_HOSTNAME__"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: provider-simulator
          namespace: smart-router
          port: 19000

